apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: submissions # for mark that this object will be group in this namespace
  name: mongo-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db" #path dimana data akan disimpan
---
apiVersion: v1
kind: PersistentVolumeClaim #kind of k8s object
metadata:
  namespace: submissions #namespace yang digunakan untuk memudahkan monitoring seluruh resource yang di deploy
  name: mongo-pvc #name of PVC
  labels:
    app: mongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
