apiVersion: v1
kind: Secret
metadata:
  namespace: submission-bmam
  name: mongo-secret
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4= #encrypted value or username
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== #encrypted value for password