apiVersion: v1
kind: ConfigMap #kind of k8s objects
metadata:
  namespace: submissions # for mark that this object will be group in this namespace
  name: mongo-configmap # name of configmap
data: 
  mongo.conf: | #mongo config, in this case for define storage's path of mongo
    storage: 
      dbPath: /data/db
  