apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: submission-bmam
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      tier: backend
  serviceName: ""
  template:
    metadata:
      labels:
        app: mongo
        tier: backend
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
            - name: mongo-configmap
              mountPath: /config
            - name: mongo-secret
              mountPath: /etc/mongo-credentials
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: mongo-configmap
          configMap:
            name: mongo-configmap
            items: 
              - key: mongo.conf
                path: mongo.conf
        - name: mongo-secret
          secret:
            secretName: mongo-secret
