version: "3.7"

services:
  item-app:
    image: ghcr.io/imamd1/item-app:v1
    ports: 
      - 80:8080
    restart: always
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: always
  
volumes:
  app-db: